# Generated by Django 2.2.5 on 2020-06-27 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты Блога',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='count_views',
            field=models.IntegerField(default=10, verbose_name='Количество просмотров'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='core.Tags', verbose_name='Тэги'),
        ),
    ]
