# Generated by Django 2.2.5 on 2020-06-27 10:10

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200627_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='need_sending',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='Слаг вакансии (url адрес)')),
                ('title', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('short_description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Краткое описание RU')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текс на главной странице RU')),
                ('count_views', models.IntegerField(default=10, verbose_name='Количество просмотров')),
                ('priority', models.IntegerField(default=10, verbose_name='Приоритет в сортировке')),
                ('availavled', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('date_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Images', verbose_name='Главное изображение вакансии')),
                ('tags', models.ManyToManyField(blank=True, related_name='vacansies', to='core.Tags', verbose_name='Тэги')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
            },
        ),
    ]
