# Generated by Django 2.2.5 on 2020-06-27 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200627_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание RU (сохраняет форматирование строк)'),
        ),
    ]
